-- 상위 카테고리
INSERT INTO CateMain (Id, Name) VALUES (24, '댄스');
INSERT INTO CateMain (Id, Name) VALUES (25, '뮤직');
INSERT INTO CateMain (Id, Name) VALUES (26, '피트니스');
INSERT INTO CateMain (Id, Name) VALUES (27, '스포츠');
INSERT INTO CateMain (Id, Name) VALUES (28, '키즈/반려동물');
INSERT INTO CateMain (Id, Name) VALUES (29, '마인드 케어');
INSERT INTO CateMain (Id, Name) VALUES (30, '메이크업');
INSERT INTO CateMain (Id, Name) VALUES (31, '스타일링');
INSERT INTO CateMain (Id, Name) VALUES (32, '재테크');
INSERT INTO CateMain (Id, Name) VALUES (33, '투잡·창업');
INSERT INTO CateMain (Id, Name) VALUES (34, '자격증/시험');
INSERT INTO CateMain (Id, Name) VALUES (35, '외국어일반');
INSERT INTO CateMain (Id, Name) VALUES (36, '드로잉·미술');
INSERT INTO CateMain (Id, Name) VALUES (37, '사진·영상');
INSERT INTO CateMain (Id, Name) VALUES (38, '글쓰기');
INSERT INTO CateMain (Id, Name) VALUES (39, '공예/DIY');
INSERT INTO CateMain (Id, Name) VALUES (40, '요리/음료');
INSERT INTO CateMain (Id, Name) VALUES (41, '새로운 취미');
INSERT INTO CateMain (Id, Name) VALUES (42, '개발/테크');
INSERT INTO CateMain (Id, Name) VALUES (43, '마케팅');
INSERT INTO CateMain (Id, Name) VALUES (44, '기획·전략·영업');
INSERT INTO CateMain (Id, Name) VALUES (45, '업무 Tool');
INSERT INTO CateMain (Id, Name) VALUES (46, '데이터');
INSERT INTO CateMain (Id, Name) VALUES (47, '취업/실무');
INSERT INTO CateMain (Id, Name) VALUES (48, '디자인');
INSERT INTO CateMain (Id, Name) VALUES (49, '영상·3D');

-- 하위 카테고리
INSERT INTO CateSub (Category, Name) VALUES (24, '연기/무용');
INSERT INTO CateSub (Category, Name) VALUES (24, '댄스');
INSERT INTO CateSub (Category, Name) VALUES (25, '작곡/디제잉');
INSERT INTO CateSub (Category, Name) VALUES (25, '악기');
INSERT INTO CateSub (Category, Name) VALUES (25, '보컬');
INSERT INTO CateSub (Category, Name) VALUES (26, '헬스/PT');
INSERT INTO CateSub (Category, Name) VALUES (26, '요가/필라테스');
INSERT INTO CateSub (Category, Name) VALUES (26, '그룹운동');
INSERT INTO CateSub (Category, Name) VALUES (27, '농구/축구/야구');
INSERT INTO CateSub (Category, Name) VALUES (27, '골프');
INSERT INTO CateSub (Category, Name) VALUES (27, '격투기');
INSERT INTO CateSub (Category, Name) VALUES (27, '생활 스포츠');
INSERT INTO CateSub (Category, Name) VALUES (27, '수상스포츠');
INSERT INTO CateSub (Category, Name) VALUES (28, '부모/육아');
INSERT INTO CateSub (Category, Name) VALUES (28, '반려동물');
INSERT INTO CateSub (Category, Name) VALUES (29, '사주/타로');
INSERT INTO CateSub (Category, Name) VALUES (29, '심리/상담/명상');
INSERT INTO CateSub (Category, Name) VALUES (29, '습관만들기');
INSERT INTO CateSub (Category, Name) VALUES (30, '메이크업');
INSERT INTO CateSub (Category, Name) VALUES (31, '패션');
INSERT INTO CateSub (Category, Name) VALUES (31, '퍼스널컬러');
INSERT INTO CateSub (Category, Name) VALUES (31, '헤어');
INSERT INTO CateSub (Category, Name) VALUES (32, '대체투자');
INSERT INTO CateSub (Category, Name) VALUES (32, '자산관리');
INSERT INTO CateSub (Category, Name) VALUES (32, '주식');
INSERT INTO CateSub (Category, Name) VALUES (32, '부동산');
INSERT INTO CateSub (Category, Name) VALUES (33, '다양한 투잡');
INSERT INTO CateSub (Category, Name) VALUES (33, '쇼핑몰');
INSERT INTO CateSub (Category, Name) VALUES (33, 'SNS');
INSERT INTO CateSub (Category, Name) VALUES (33, '창업');
INSERT INTO CateSub (Category, Name) VALUES (34, '어학자격증');
INSERT INTO CateSub (Category, Name) VALUES (34, '기타 외국어');
INSERT INTO CateSub (Category, Name) VALUES (35, '영어');
INSERT INTO CateSub (Category, Name) VALUES (35, '일본어');
INSERT INTO CateSub (Category, Name) VALUES (35, '중국어');
INSERT INTO CateSub (Category, Name) VALUES (36, '취미미술');
INSERT INTO CateSub (Category, Name) VALUES (36, '디지털드로잉');
INSERT INTO CateSub (Category, Name) VALUES (36, '캘리그래피');
INSERT INTO CateSub (Category, Name) VALUES (37, '사진');
INSERT INTO CateSub (Category, Name) VALUES (38, '출판');
INSERT INTO CateSub (Category, Name) VALUES (38, '글쓰기');
INSERT INTO CateSub (Category, Name) VALUES (39, '플라워');
INSERT INTO CateSub (Category, Name) VALUES (39, '가죽/목공/도예');
INSERT INTO CateSub (Category, Name) VALUES (39, '인테리어');
INSERT INTO CateSub (Category, Name) VALUES (39, '향/초/비누');
INSERT INTO CateSub (Category, Name) VALUES (40, '요리/베이킹');
INSERT INTO CateSub (Category, Name) VALUES (40, '커피/차/술');
INSERT INTO CateSub (Category, Name) VALUES (41, '새로운 취미');
INSERT INTO CateSub (Category, Name) VALUES (42, '프론트엔드');
INSERT INTO CateSub (Category, Name) VALUES (42, '모바일');
INSERT INTO CateSub (Category, Name) VALUES (42, 'ML/AI');
INSERT INTO CateSub (Category, Name) VALUES (42, '개발 입문');
INSERT INTO CateSub (Category, Name) VALUES (42, '개발 공통');
INSERT INTO CateSub (Category, Name) VALUES (42, '백엔드');
INSERT INTO CateSub (Category, Name) VALUES (43, '콘텐츠 마케팅');
INSERT INTO CateSub (Category, Name) VALUES (43, '퍼포먼스 마케팅');
INSERT INTO CateSub (Category, Name) VALUES (43, 'GA/Pixel');
INSERT INTO CateSub (Category, Name) VALUES (43, '마케팅 일반');
INSERT INTO CateSub (Category, Name) VALUES (44, '서비스 기획/PM');
INSERT INTO CateSub (Category, Name) VALUES (44, '보고·발표');
INSERT INTO CateSub (Category, Name) VALUES (45, 'PPT');
INSERT INTO CateSub (Category, Name) VALUES (45, '엑셀');
INSERT INTO CateSub (Category, Name) VALUES (45, '협업 Tool');
INSERT INTO CateSub (Category, Name) VALUES (46, 'SQL');
INSERT INTO CateSub (Category, Name) VALUES (46, '시각화');
INSERT INTO CateSub (Category, Name) VALUES (46, '논문/통계');
INSERT INTO CateSub (Category, Name) VALUES (46, 'Python/R');
INSERT INTO CateSub (Category, Name) VALUES (47, '자격증/시험');
INSERT INTO CateSub (Category, Name) VALUES (47, '인문/교양');
INSERT INTO CateSub (Category, Name) VALUES (47, '취업/이직');
INSERT INTO CateSub (Category, Name) VALUES (47, '재무/세무/회계');
INSERT INTO CateSub (Category, Name) VALUES (47, '스피치');
INSERT INTO CateSub (Category, Name) VALUES (48, 'UX/UI');
INSERT INTO CateSub (Category, Name) VALUES (48, '제품 디자인');
INSERT INTO CateSub (Category, Name) VALUES (48, '편집 디자인');
INSERT INTO CateSub (Category, Name) VALUES (48, '일러스트레이션');
INSERT INTO CateSub (Category, Name) VALUES (48, '건축');
INSERT INTO CateSub (Category, Name) VALUES (48, '브랜드 디자인');
INSERT INTO CateSub (Category, Name) VALUES (49, '영상기획/제작');
INSERT INTO CateSub (Category, Name) VALUES (49, '영상 촬영');
INSERT INTO CateSub (Category, Name) VALUES (49, '편집/보정');
INSERT INTO CateSub (Category, Name) VALUES (49, '크리에이터');

-- 사용자
INSERT INTO Accounts(Id, name, ContactEmail) Values (1, 'Timo', 'timo@taling.me');